<?php

declare(strict_types=1);

namespace Yosina\Transliterators;

use Yosina\Char;
use Yosina\TransliteratorInterface;

/**
 * Replace circled or squared characters with templated forms.
 */
class CircledOrSquaredTransliterator implements TransliteratorInterface
{
    private const MAPPINGS = [
        '©' => ['rendering' => "C", 'type' => "circle", 'emoji' => false],
        '℗' => ['rendering' => "P", 'type' => "circle", 'emoji' => false],
        '①' => ['rendering' => "1", 'type' => "circle", 'emoji' => false],
        '②' => ['rendering' => "2", 'type' => "circle", 'emoji' => false],
        '③' => ['rendering' => "3", 'type' => "circle", 'emoji' => false],
        '④' => ['rendering' => "4", 'type' => "circle", 'emoji' => false],
        '⑤' => ['rendering' => "5", 'type' => "circle", 'emoji' => false],
        '⑥' => ['rendering' => "6", 'type' => "circle", 'emoji' => false],
        '⑦' => ['rendering' => "7", 'type' => "circle", 'emoji' => false],
        '⑧' => ['rendering' => "8", 'type' => "circle", 'emoji' => false],
        '⑨' => ['rendering' => "9", 'type' => "circle", 'emoji' => false],
        '⑩' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '⑪' => ['rendering' => "11", 'type' => "circle", 'emoji' => false],
        '⑫' => ['rendering' => "12", 'type' => "circle", 'emoji' => false],
        '⑬' => ['rendering' => "13", 'type' => "circle", 'emoji' => false],
        '⑭' => ['rendering' => "14", 'type' => "circle", 'emoji' => false],
        '⑮' => ['rendering' => "15", 'type' => "circle", 'emoji' => false],
        '⑯' => ['rendering' => "16", 'type' => "circle", 'emoji' => false],
        '⑰' => ['rendering' => "17", 'type' => "circle", 'emoji' => false],
        '⑱' => ['rendering' => "18", 'type' => "circle", 'emoji' => false],
        '⑲' => ['rendering' => "19", 'type' => "circle", 'emoji' => false],
        '⑳' => ['rendering' => "20", 'type' => "circle", 'emoji' => false],
        'Ⓐ' => ['rendering' => "A", 'type' => "circle", 'emoji' => false],
        'Ⓑ' => ['rendering' => "B", 'type' => "circle", 'emoji' => false],
        'Ⓒ' => ['rendering' => "C", 'type' => "circle", 'emoji' => false],
        'Ⓓ' => ['rendering' => "D", 'type' => "circle", 'emoji' => false],
        'Ⓔ' => ['rendering' => "E", 'type' => "circle", 'emoji' => false],
        'Ⓕ' => ['rendering' => "F", 'type' => "circle", 'emoji' => false],
        'Ⓖ' => ['rendering' => "G", 'type' => "circle", 'emoji' => false],
        'Ⓗ' => ['rendering' => "H", 'type' => "circle", 'emoji' => false],
        'Ⓘ' => ['rendering' => "I", 'type' => "circle", 'emoji' => false],
        'Ⓙ' => ['rendering' => "J", 'type' => "circle", 'emoji' => false],
        'Ⓚ' => ['rendering' => "K", 'type' => "circle", 'emoji' => false],
        'Ⓛ' => ['rendering' => "L", 'type' => "circle", 'emoji' => false],
        'Ⓜ' => ['rendering' => "M", 'type' => "circle", 'emoji' => false],
        'Ⓝ' => ['rendering' => "N", 'type' => "circle", 'emoji' => false],
        'Ⓞ' => ['rendering' => "O", 'type' => "circle", 'emoji' => false],
        'Ⓟ' => ['rendering' => "P", 'type' => "circle", 'emoji' => false],
        'Ⓠ' => ['rendering' => "Q", 'type' => "circle", 'emoji' => false],
        'Ⓡ' => ['rendering' => "R", 'type' => "circle", 'emoji' => false],
        'Ⓢ' => ['rendering' => "S", 'type' => "circle", 'emoji' => false],
        'Ⓣ' => ['rendering' => "T", 'type' => "circle", 'emoji' => false],
        'Ⓤ' => ['rendering' => "U", 'type' => "circle", 'emoji' => false],
        'Ⓥ' => ['rendering' => "V", 'type' => "circle", 'emoji' => false],
        'Ⓦ' => ['rendering' => "W", 'type' => "circle", 'emoji' => false],
        'Ⓧ' => ['rendering' => "X", 'type' => "circle", 'emoji' => false],
        'Ⓨ' => ['rendering' => "Y", 'type' => "circle", 'emoji' => false],
        'Ⓩ' => ['rendering' => "Z", 'type' => "circle", 'emoji' => false],
        'ⓐ' => ['rendering' => "a", 'type' => "circle", 'emoji' => false],
        'ⓑ' => ['rendering' => "b", 'type' => "circle", 'emoji' => false],
        'ⓒ' => ['rendering' => "c", 'type' => "circle", 'emoji' => false],
        'ⓓ' => ['rendering' => "d", 'type' => "circle", 'emoji' => false],
        'ⓔ' => ['rendering' => "e", 'type' => "circle", 'emoji' => false],
        'ⓕ' => ['rendering' => "f", 'type' => "circle", 'emoji' => false],
        'ⓖ' => ['rendering' => "g", 'type' => "circle", 'emoji' => false],
        'ⓗ' => ['rendering' => "h", 'type' => "circle", 'emoji' => false],
        'ⓘ' => ['rendering' => "i", 'type' => "circle", 'emoji' => false],
        'ⓙ' => ['rendering' => "j", 'type' => "circle", 'emoji' => false],
        'ⓚ' => ['rendering' => "k", 'type' => "circle", 'emoji' => false],
        'ⓛ' => ['rendering' => "l", 'type' => "circle", 'emoji' => false],
        'ⓜ' => ['rendering' => "m", 'type' => "circle", 'emoji' => false],
        'ⓝ' => ['rendering' => "n", 'type' => "circle", 'emoji' => false],
        'ⓞ' => ['rendering' => "o", 'type' => "circle", 'emoji' => false],
        'ⓟ' => ['rendering' => "p", 'type' => "circle", 'emoji' => false],
        'ⓠ' => ['rendering' => "q", 'type' => "circle", 'emoji' => false],
        'ⓡ' => ['rendering' => "r", 'type' => "circle", 'emoji' => false],
        'ⓢ' => ['rendering' => "s", 'type' => "circle", 'emoji' => false],
        'ⓣ' => ['rendering' => "t", 'type' => "circle", 'emoji' => false],
        'ⓤ' => ['rendering' => "u", 'type' => "circle", 'emoji' => false],
        'ⓥ' => ['rendering' => "v", 'type' => "circle", 'emoji' => false],
        'ⓦ' => ['rendering' => "w", 'type' => "circle", 'emoji' => false],
        'ⓧ' => ['rendering' => "x", 'type' => "circle", 'emoji' => false],
        'ⓨ' => ['rendering' => "y", 'type' => "circle", 'emoji' => false],
        'ⓩ' => ['rendering' => "z", 'type' => "circle", 'emoji' => false],
        '⓪' => ['rendering' => "0", 'type' => "circle", 'emoji' => false],
        '⓫' => ['rendering' => "11", 'type' => "circle", 'emoji' => false],
        '⓬' => ['rendering' => "12", 'type' => "circle", 'emoji' => false],
        '⓭' => ['rendering' => "13", 'type' => "circle", 'emoji' => false],
        '⓮' => ['rendering' => "14", 'type' => "circle", 'emoji' => false],
        '⓯' => ['rendering' => "15", 'type' => "circle", 'emoji' => false],
        '⓰' => ['rendering' => "16", 'type' => "circle", 'emoji' => false],
        '⓱' => ['rendering' => "17", 'type' => "circle", 'emoji' => false],
        '⓲' => ['rendering' => "18", 'type' => "circle", 'emoji' => false],
        '⓳' => ['rendering' => "19", 'type' => "circle", 'emoji' => false],
        '⓴' => ['rendering' => "20", 'type' => "circle", 'emoji' => false],
        '⓵' => ['rendering' => "1", 'type' => "circle", 'emoji' => false],
        '⓶' => ['rendering' => "2", 'type' => "circle", 'emoji' => false],
        '⓷' => ['rendering' => "3", 'type' => "circle", 'emoji' => false],
        '⓸' => ['rendering' => "4", 'type' => "circle", 'emoji' => false],
        '⓹' => ['rendering' => "5", 'type' => "circle", 'emoji' => false],
        '⓺' => ['rendering' => "6", 'type' => "circle", 'emoji' => false],
        '⓻' => ['rendering' => "7", 'type' => "circle", 'emoji' => false],
        '⓼' => ['rendering' => "8", 'type' => "circle", 'emoji' => false],
        '⓽' => ['rendering' => "9", 'type' => "circle", 'emoji' => false],
        '⓾' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '⓿' => ['rendering' => "0", 'type' => "circle", 'emoji' => false],
        '❶' => ['rendering' => "1", 'type' => "circle", 'emoji' => false],
        '❷' => ['rendering' => "2", 'type' => "circle", 'emoji' => false],
        '❸' => ['rendering' => "3", 'type' => "circle", 'emoji' => false],
        '❹' => ['rendering' => "4", 'type' => "circle", 'emoji' => false],
        '❺' => ['rendering' => "5", 'type' => "circle", 'emoji' => false],
        '❻' => ['rendering' => "6", 'type' => "circle", 'emoji' => false],
        '❼' => ['rendering' => "7", 'type' => "circle", 'emoji' => false],
        '❽' => ['rendering' => "8", 'type' => "circle", 'emoji' => false],
        '❾' => ['rendering' => "9", 'type' => "circle", 'emoji' => false],
        '❿' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '➀' => ['rendering' => "1", 'type' => "circle", 'emoji' => false],
        '➁' => ['rendering' => "2", 'type' => "circle", 'emoji' => false],
        '➂' => ['rendering' => "3", 'type' => "circle", 'emoji' => false],
        '➃' => ['rendering' => "4", 'type' => "circle", 'emoji' => false],
        '➄' => ['rendering' => "5", 'type' => "circle", 'emoji' => false],
        '➅' => ['rendering' => "6", 'type' => "circle", 'emoji' => false],
        '➆' => ['rendering' => "7", 'type' => "circle", 'emoji' => false],
        '➇' => ['rendering' => "8", 'type' => "circle", 'emoji' => false],
        '➈' => ['rendering' => "9", 'type' => "circle", 'emoji' => false],
        '➉' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '➊' => ['rendering' => "1", 'type' => "circle", 'emoji' => false],
        '➋' => ['rendering' => "2", 'type' => "circle", 'emoji' => false],
        '➌' => ['rendering' => "3", 'type' => "circle", 'emoji' => false],
        '➍' => ['rendering' => "4", 'type' => "circle", 'emoji' => false],
        '➎' => ['rendering' => "5", 'type' => "circle", 'emoji' => false],
        '➏' => ['rendering' => "6", 'type' => "circle", 'emoji' => false],
        '➐' => ['rendering' => "7", 'type' => "circle", 'emoji' => false],
        '➑' => ['rendering' => "8", 'type' => "circle", 'emoji' => false],
        '➒' => ['rendering' => "9", 'type' => "circle", 'emoji' => false],
        '➓' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '〶' => ['rendering' => '〒', 'type' => "circle", 'emoji' => false],
        '㉄' => ['rendering' => '問', 'type' => "circle", 'emoji' => false],
        '㉅' => ['rendering' => '幼', 'type' => "circle", 'emoji' => false],
        '㉆' => ['rendering' => '文', 'type' => "circle", 'emoji' => false],
        '㉇' => ['rendering' => '箏', 'type' => "circle", 'emoji' => false],
        '㉈' => ['rendering' => "10", 'type' => "circle", 'emoji' => false],
        '㉑' => ['rendering' => "21", 'type' => "circle", 'emoji' => false],
        '㉒' => ['rendering' => "22", 'type' => "circle", 'emoji' => false],
        '㉓' => ['rendering' => "23", 'type' => "circle", 'emoji' => false],
        '㉔' => ['rendering' => "24", 'type' => "circle", 'emoji' => false],
        '㉕' => ['rendering' => "25", 'type' => "circle", 'emoji' => false],
        '㉖' => ['rendering' => "26", 'type' => "circle", 'emoji' => false],
        '㉗' => ['rendering' => "27", 'type' => "circle", 'emoji' => false],
        '㉘' => ['rendering' => "28", 'type' => "circle", 'emoji' => false],
        '㉙' => ['rendering' => "29", 'type' => "circle", 'emoji' => false],
        '㉚' => ['rendering' => "30", 'type' => "circle", 'emoji' => false],
        '㉛' => ['rendering' => "31", 'type' => "circle", 'emoji' => false],
        '㉜' => ['rendering' => "32", 'type' => "circle", 'emoji' => false],
        '㉝' => ['rendering' => "33", 'type' => "circle", 'emoji' => false],
        '㉞' => ['rendering' => "34", 'type' => "circle", 'emoji' => false],
        '㉟' => ['rendering' => "35", 'type' => "circle", 'emoji' => false],
        '㊀' => ['rendering' => '一', 'type' => "circle", 'emoji' => false],
        '㊁' => ['rendering' => '二', 'type' => "circle", 'emoji' => false],
        '㊂' => ['rendering' => '三', 'type' => "circle", 'emoji' => false],
        '㊃' => ['rendering' => '四', 'type' => "circle", 'emoji' => false],
        '㊄' => ['rendering' => '五', 'type' => "circle", 'emoji' => false],
        '㊅' => ['rendering' => '六', 'type' => "circle", 'emoji' => false],
        '㊆' => ['rendering' => '七', 'type' => "circle", 'emoji' => false],
        '㊇' => ['rendering' => '八', 'type' => "circle", 'emoji' => false],
        '㊈' => ['rendering' => '九', 'type' => "circle", 'emoji' => false],
        '㊉' => ['rendering' => '十', 'type' => "circle", 'emoji' => false],
        '㊊' => ['rendering' => '月', 'type' => "circle", 'emoji' => false],
        '㊋' => ['rendering' => '火', 'type' => "circle", 'emoji' => false],
        '㊌' => ['rendering' => '水', 'type' => "circle", 'emoji' => false],
        '㊍' => ['rendering' => '木', 'type' => "circle", 'emoji' => false],
        '㊎' => ['rendering' => '金', 'type' => "circle", 'emoji' => false],
        '㊏' => ['rendering' => '土', 'type' => "circle", 'emoji' => false],
        '㊐' => ['rendering' => '日', 'type' => "circle", 'emoji' => false],
        '㊑' => ['rendering' => '株', 'type' => "circle", 'emoji' => false],
        '㊒' => ['rendering' => '有', 'type' => "circle", 'emoji' => false],
        '㊓' => ['rendering' => '社', 'type' => "circle", 'emoji' => false],
        '㊔' => ['rendering' => '名', 'type' => "circle", 'emoji' => false],
        '㊕' => ['rendering' => '特', 'type' => "circle", 'emoji' => false],
        '㊖' => ['rendering' => '財', 'type' => "circle", 'emoji' => false],
        '㊗' => ['rendering' => '祝', 'type' => "circle", 'emoji' => false],
        '㊘' => ['rendering' => '労', 'type' => "circle", 'emoji' => false],
        '㊙' => ['rendering' => '秘', 'type' => "circle", 'emoji' => false],
        '㊚' => ['rendering' => '男', 'type' => "circle", 'emoji' => false],
        '㊛' => ['rendering' => '女', 'type' => "circle", 'emoji' => false],
        '㊜' => ['rendering' => '適', 'type' => "circle", 'emoji' => false],
        '㊝' => ['rendering' => '優', 'type' => "circle", 'emoji' => false],
        '㊞' => ['rendering' => '印', 'type' => "circle", 'emoji' => false],
        '㊟' => ['rendering' => '注', 'type' => "circle", 'emoji' => false],
        '㊠' => ['rendering' => '項', 'type' => "circle", 'emoji' => false],
        '㊡' => ['rendering' => '休', 'type' => "circle", 'emoji' => false],
        '㊢' => ['rendering' => '写', 'type' => "circle", 'emoji' => false],
        '㊣' => ['rendering' => '正', 'type' => "circle", 'emoji' => false],
        '㊤' => ['rendering' => '上', 'type' => "circle", 'emoji' => false],
        '㊥' => ['rendering' => '中', 'type' => "circle", 'emoji' => false],
        '㊦' => ['rendering' => '下', 'type' => "circle", 'emoji' => false],
        '㊧' => ['rendering' => '左', 'type' => "circle", 'emoji' => false],
        '㊨' => ['rendering' => '右', 'type' => "circle", 'emoji' => false],
        '㊩' => ['rendering' => '医', 'type' => "circle", 'emoji' => false],
        '㊪' => ['rendering' => '宗', 'type' => "circle", 'emoji' => false],
        '㊫' => ['rendering' => '学', 'type' => "circle", 'emoji' => false],
        '㊬' => ['rendering' => '監', 'type' => "circle", 'emoji' => false],
        '㊭' => ['rendering' => '企', 'type' => "circle", 'emoji' => false],
        '㊮' => ['rendering' => '資', 'type' => "circle", 'emoji' => false],
        '㊯' => ['rendering' => '協', 'type' => "circle", 'emoji' => false],
        '㊰' => ['rendering' => '夜', 'type' => "circle", 'emoji' => false],
        '㊱' => ['rendering' => "36", 'type' => "circle", 'emoji' => false],
        '㊲' => ['rendering' => "37", 'type' => "circle", 'emoji' => false],
        '㊳' => ['rendering' => "38", 'type' => "circle", 'emoji' => false],
        '㊴' => ['rendering' => "39", 'type' => "circle", 'emoji' => false],
        '㊵' => ['rendering' => "40", 'type' => "circle", 'emoji' => false],
        '㊶' => ['rendering' => "41", 'type' => "circle", 'emoji' => false],
        '㊷' => ['rendering' => "42", 'type' => "circle", 'emoji' => false],
        '㊸' => ['rendering' => "43", 'type' => "circle", 'emoji' => false],
        '㊹' => ['rendering' => "44", 'type' => "circle", 'emoji' => false],
        '㊺' => ['rendering' => "45", 'type' => "circle", 'emoji' => false],
        '㊻' => ['rendering' => "46", 'type' => "circle", 'emoji' => false],
        '㊼' => ['rendering' => "47", 'type' => "circle", 'emoji' => false],
        '㊽' => ['rendering' => "48", 'type' => "circle", 'emoji' => false],
        '㊾' => ['rendering' => "49", 'type' => "circle", 'emoji' => false],
        '㊿' => ['rendering' => "50", 'type' => "circle", 'emoji' => false],
        '㋐' => ['rendering' => 'ア', 'type' => "circle", 'emoji' => false],
        '㋑' => ['rendering' => 'イ', 'type' => "circle", 'emoji' => false],
        '㋒' => ['rendering' => 'ウ', 'type' => "circle", 'emoji' => false],
        '㋓' => ['rendering' => 'エ', 'type' => "circle", 'emoji' => false],
        '㋔' => ['rendering' => 'オ', 'type' => "circle", 'emoji' => false],
        '㋕' => ['rendering' => 'カ', 'type' => "circle", 'emoji' => false],
        '㋖' => ['rendering' => 'キ', 'type' => "circle", 'emoji' => false],
        '㋗' => ['rendering' => 'ク', 'type' => "circle", 'emoji' => false],
        '㋘' => ['rendering' => 'ケ', 'type' => "circle", 'emoji' => false],
        '㋙' => ['rendering' => 'コ', 'type' => "circle", 'emoji' => false],
        '㋚' => ['rendering' => 'サ', 'type' => "circle", 'emoji' => false],
        '㋛' => ['rendering' => 'シ', 'type' => "circle", 'emoji' => false],
        '㋜' => ['rendering' => 'ス', 'type' => "circle", 'emoji' => false],
        '㋝' => ['rendering' => 'セ', 'type' => "circle", 'emoji' => false],
        '㋞' => ['rendering' => 'ソ', 'type' => "circle", 'emoji' => false],
        '㋟' => ['rendering' => 'タ', 'type' => "circle", 'emoji' => false],
        '㋠' => ['rendering' => 'チ', 'type' => "circle", 'emoji' => false],
        '㋡' => ['rendering' => 'ツ', 'type' => "circle", 'emoji' => false],
        '㋢' => ['rendering' => 'テ', 'type' => "circle", 'emoji' => false],
        '㋣' => ['rendering' => 'ト', 'type' => "circle", 'emoji' => false],
        '㋤' => ['rendering' => 'ナ', 'type' => "circle", 'emoji' => false],
        '㋥' => ['rendering' => 'ニ', 'type' => "circle", 'emoji' => false],
        '㋦' => ['rendering' => 'ヌ', 'type' => "circle", 'emoji' => false],
        '㋧' => ['rendering' => 'ネ', 'type' => "circle", 'emoji' => false],
        '㋨' => ['rendering' => 'ノ', 'type' => "circle", 'emoji' => false],
        '㋩' => ['rendering' => 'ハ', 'type' => "circle", 'emoji' => false],
        '㋪' => ['rendering' => 'ヒ', 'type' => "circle", 'emoji' => false],
        '㋫' => ['rendering' => 'フ', 'type' => "circle", 'emoji' => false],
        '㋬' => ['rendering' => 'ヘ', 'type' => "circle", 'emoji' => false],
        '㋭' => ['rendering' => 'ホ', 'type' => "circle", 'emoji' => false],
        '㋮' => ['rendering' => 'マ', 'type' => "circle", 'emoji' => false],
        '㋯' => ['rendering' => 'ミ', 'type' => "circle", 'emoji' => false],
        '㋰' => ['rendering' => 'ム', 'type' => "circle", 'emoji' => false],
        '㋱' => ['rendering' => 'メ', 'type' => "circle", 'emoji' => false],
        '㋲' => ['rendering' => 'モ', 'type' => "circle", 'emoji' => false],
        '㋳' => ['rendering' => 'ヤ', 'type' => "circle", 'emoji' => false],
        '㋴' => ['rendering' => 'ユ', 'type' => "circle", 'emoji' => false],
        '㋵' => ['rendering' => 'ヨ', 'type' => "circle", 'emoji' => false],
        '㋶' => ['rendering' => 'ラ', 'type' => "circle", 'emoji' => false],
        '㋷' => ['rendering' => 'リ', 'type' => "circle", 'emoji' => false],
        '㋸' => ['rendering' => 'ル', 'type' => "circle", 'emoji' => false],
        '㋹' => ['rendering' => 'レ', 'type' => "circle", 'emoji' => false],
        '㋺' => ['rendering' => 'ロ', 'type' => "circle", 'emoji' => false],
        '㋻' => ['rendering' => 'ワ', 'type' => "circle", 'emoji' => false],
        '㋼' => ['rendering' => 'ヰ', 'type' => "circle", 'emoji' => false],
        '㋽' => ['rendering' => 'ヱ', 'type' => "circle", 'emoji' => false],
        '㋾' => ['rendering' => 'ヲ', 'type' => "circle", 'emoji' => false],
        '🄋' => ['rendering' => "0", 'type' => "circle", 'emoji' => false],
        '🄌' => ['rendering' => "0", 'type' => "circle", 'emoji' => false],
        '🄫' => ['rendering' => "C", 'type' => "circle", 'emoji' => false],
        '🄬' => ['rendering' => "R", 'type' => "circle", 'emoji' => false],
        '🄭' => ['rendering' => "CD", 'type' => "circle", 'emoji' => false],
        '🄮' => ['rendering' => "WZ", 'type' => "circle", 'emoji' => false],
        '🄰' => ['rendering' => "A", 'type' => "square", 'emoji' => false],
        '🄱' => ['rendering' => "B", 'type' => "square", 'emoji' => false],
        '🄲' => ['rendering' => "C", 'type' => "square", 'emoji' => false],
        '🄳' => ['rendering' => "D", 'type' => "square", 'emoji' => false],
        '🄴' => ['rendering' => "E", 'type' => "square", 'emoji' => false],
        '🄵' => ['rendering' => "F", 'type' => "square", 'emoji' => false],
        '🄶' => ['rendering' => "G", 'type' => "square", 'emoji' => false],
        '🄷' => ['rendering' => "H", 'type' => "square", 'emoji' => false],
        '🄸' => ['rendering' => "I", 'type' => "square", 'emoji' => false],
        '🄹' => ['rendering' => "J", 'type' => "square", 'emoji' => false],
        '🄺' => ['rendering' => "K", 'type' => "square", 'emoji' => false],
        '🄻' => ['rendering' => "L", 'type' => "square", 'emoji' => false],
        '🄼' => ['rendering' => "M", 'type' => "square", 'emoji' => false],
        '🄽' => ['rendering' => "N", 'type' => "square", 'emoji' => false],
        '🄾' => ['rendering' => "O", 'type' => "square", 'emoji' => false],
        '🄿' => ['rendering' => "P", 'type' => "square", 'emoji' => false],
        '🅀' => ['rendering' => "Q", 'type' => "square", 'emoji' => false],
        '🅁' => ['rendering' => "R", 'type' => "square", 'emoji' => false],
        '🅂' => ['rendering' => "S", 'type' => "square", 'emoji' => false],
        '🅃' => ['rendering' => "T", 'type' => "square", 'emoji' => false],
        '🅄' => ['rendering' => "U", 'type' => "square", 'emoji' => false],
        '🅅' => ['rendering' => "V", 'type' => "square", 'emoji' => false],
        '🅆' => ['rendering' => "W", 'type' => "square", 'emoji' => false],
        '🅇' => ['rendering' => "X", 'type' => "square", 'emoji' => false],
        '🅈' => ['rendering' => "Y", 'type' => "square", 'emoji' => false],
        '🅉' => ['rendering' => "Z", 'type' => "square", 'emoji' => false],
        '🅊' => ['rendering' => "HV", 'type' => "square", 'emoji' => false],
        '🅋' => ['rendering' => "MV", 'type' => "square", 'emoji' => false],
        '🅌' => ['rendering' => "SD", 'type' => "square", 'emoji' => false],
        '🅍' => ['rendering' => "SS", 'type' => "square", 'emoji' => false],
        '🅎' => ['rendering' => "PPV", 'type' => "square", 'emoji' => false],
        '🅏' => ['rendering' => "WC", 'type' => "square", 'emoji' => false],
        '🅐' => ['rendering' => "A", 'type' => "circle", 'emoji' => false],
        '🅑' => ['rendering' => "B", 'type' => "circle", 'emoji' => false],
        '🅒' => ['rendering' => "C", 'type' => "circle", 'emoji' => false],
        '🅓' => ['rendering' => "D", 'type' => "circle", 'emoji' => false],
        '🅔' => ['rendering' => "E", 'type' => "circle", 'emoji' => false],
        '🅕' => ['rendering' => "F", 'type' => "circle", 'emoji' => false],
        '🅖' => ['rendering' => "G", 'type' => "circle", 'emoji' => false],
        '🅗' => ['rendering' => "H", 'type' => "circle", 'emoji' => false],
        '🅘' => ['rendering' => "I", 'type' => "circle", 'emoji' => false],
        '🅙' => ['rendering' => "J", 'type' => "circle", 'emoji' => false],
        '🅚' => ['rendering' => "K", 'type' => "circle", 'emoji' => false],
        '🅛' => ['rendering' => "L", 'type' => "circle", 'emoji' => false],
        '🅜' => ['rendering' => "M", 'type' => "circle", 'emoji' => false],
        '🅝' => ['rendering' => "N", 'type' => "circle", 'emoji' => false],
        '🅞' => ['rendering' => "O", 'type' => "circle", 'emoji' => false],
        '🅟' => ['rendering' => "P", 'type' => "circle", 'emoji' => false],
        '🅠' => ['rendering' => "Q", 'type' => "circle", 'emoji' => false],
        '🅡' => ['rendering' => "R", 'type' => "circle", 'emoji' => false],
        '🅢' => ['rendering' => "S", 'type' => "circle", 'emoji' => false],
        '🅣' => ['rendering' => "T", 'type' => "circle", 'emoji' => false],
        '🅤' => ['rendering' => "U", 'type' => "circle", 'emoji' => false],
        '🅥' => ['rendering' => "V", 'type' => "circle", 'emoji' => false],
        '🅦' => ['rendering' => "W", 'type' => "circle", 'emoji' => false],
        '🅧' => ['rendering' => "X", 'type' => "circle", 'emoji' => false],
        '🅨' => ['rendering' => "Y", 'type' => "circle", 'emoji' => false],
        '🅩' => ['rendering' => "Z", 'type' => "circle", 'emoji' => false],
        '🅰' => ['rendering' => "A", 'type' => "square", 'emoji' => false],
        '🅱' => ['rendering' => "B", 'type' => "square", 'emoji' => false],
        '🅲' => ['rendering' => "C", 'type' => "square", 'emoji' => false],
        '🅳' => ['rendering' => "D", 'type' => "square", 'emoji' => false],
        '🅴' => ['rendering' => "E", 'type' => "square", 'emoji' => false],
        '🅵' => ['rendering' => "F", 'type' => "square", 'emoji' => false],
        '🅶' => ['rendering' => "G", 'type' => "square", 'emoji' => false],
        '🅷' => ['rendering' => "H", 'type' => "square", 'emoji' => false],
        '🅸' => ['rendering' => "I", 'type' => "square", 'emoji' => false],
        '🅹' => ['rendering' => "J", 'type' => "square", 'emoji' => false],
        '🅺' => ['rendering' => "K", 'type' => "square", 'emoji' => false],
        '🅻' => ['rendering' => "L", 'type' => "square", 'emoji' => false],
        '🅼' => ['rendering' => "M", 'type' => "square", 'emoji' => false],
        '🅽' => ['rendering' => "N", 'type' => "square", 'emoji' => false],
        '🅾' => ['rendering' => "O", 'type' => "square", 'emoji' => false],
        '🅿' => ['rendering' => "P", 'type' => "square", 'emoji' => false],
        '🆀' => ['rendering' => "Q", 'type' => "square", 'emoji' => false],
        '🆁' => ['rendering' => "R", 'type' => "square", 'emoji' => false],
        '🆂' => ['rendering' => "S", 'type' => "square", 'emoji' => false],
        '🆃' => ['rendering' => "T", 'type' => "square", 'emoji' => false],
        '🆄' => ['rendering' => "U", 'type' => "square", 'emoji' => false],
        '🆅' => ['rendering' => "V", 'type' => "square", 'emoji' => false],
        '🆆' => ['rendering' => "W", 'type' => "square", 'emoji' => false],
        '🆇' => ['rendering' => "X", 'type' => "square", 'emoji' => false],
        '🆈' => ['rendering' => "Y", 'type' => "square", 'emoji' => false],
        '🆉' => ['rendering' => "Z", 'type' => "square", 'emoji' => false],
        '🆋' => ['rendering' => "IC", 'type' => "square", 'emoji' => false],
        '🆌' => ['rendering' => "PA", 'type' => "square", 'emoji' => false],
        '🆍' => ['rendering' => "SA", 'type' => "square", 'emoji' => false],
        '🆎' => ['rendering' => "AB", 'type' => "square", 'emoji' => true],
        '🆏' => ['rendering' => "WC", 'type' => "square", 'emoji' => false],
        '🆐' => ['rendering' => "DJ", 'type' => "square", 'emoji' => false],
        '🆑' => ['rendering' => "CL", 'type' => "square", 'emoji' => true],
        '🆒' => ['rendering' => "COOL", 'type' => "square", 'emoji' => true],
        '🆓' => ['rendering' => "FREE", 'type' => "square", 'emoji' => true],
        '🆔' => ['rendering' => "ID", 'type' => "square", 'emoji' => true],
        '🆕' => ['rendering' => "NEW", 'type' => "square", 'emoji' => true],
        '🆖' => ['rendering' => "NG", 'type' => "square", 'emoji' => true],
        '🆗' => ['rendering' => "OK", 'type' => "square", 'emoji' => true],
        '🆘' => ['rendering' => "SOS", 'type' => "square", 'emoji' => true],
        '🆙' => ['rendering' => "UP!", 'type' => "square", 'emoji' => true],
        '🆚' => ['rendering' => "VS", 'type' => "square", 'emoji' => true],
        '🆛' => ['rendering' => "3D", 'type' => "square", 'emoji' => false],
        '🆜' => ['rendering' => "2ndScr", 'type' => "square", 'emoji' => false],
        '🆝' => ['rendering' => "2K", 'type' => "square", 'emoji' => false],
        '🆞' => ['rendering' => "4K", 'type' => "square", 'emoji' => false],
        '🆟' => ['rendering' => "8K", 'type' => "square", 'emoji' => false],
        '🆠' => ['rendering' => "5.1", 'type' => "square", 'emoji' => false],
        '🆡' => ['rendering' => "7.1", 'type' => "square", 'emoji' => false],
        '🆢' => ['rendering' => "22.2", 'type' => "square", 'emoji' => false],
        '🆣' => ['rendering' => "60P", 'type' => "square", 'emoji' => false],
        '🆤' => ['rendering' => "120P", 'type' => "square", 'emoji' => false],
        '🆥' => ['rendering' => "d", 'type' => "square", 'emoji' => false],
        '🆦' => ['rendering' => "HC", 'type' => "square", 'emoji' => false],
        '🆧' => ['rendering' => "HDR", 'type' => "square", 'emoji' => false],
        '🆨' => ['rendering' => "Hi-Res", 'type' => "square", 'emoji' => false],
        '🆩' => ['rendering' => "Lossless", 'type' => "square", 'emoji' => false],
        '🆪' => ['rendering' => "SHV", 'type' => "square", 'emoji' => false],
        '🆫' => ['rendering' => "UHD", 'type' => "square", 'emoji' => false],
        '🆬' => ['rendering' => "VOD", 'type' => "square", 'emoji' => false],
        '🆭' => ['rendering' => "M", 'type' => "circle", 'emoji' => false],
        '🇦' => ['rendering' => "A", 'type' => "square", 'emoji' => false],
        '🇧' => ['rendering' => "B", 'type' => "square", 'emoji' => false],
        '🇨' => ['rendering' => "C", 'type' => "square", 'emoji' => false],
        '🇩' => ['rendering' => "D", 'type' => "square", 'emoji' => false],
        '🇪' => ['rendering' => "E", 'type' => "square", 'emoji' => false],
        '🇫' => ['rendering' => "F", 'type' => "square", 'emoji' => false],
        '🇬' => ['rendering' => "G", 'type' => "square", 'emoji' => false],
        '🇭' => ['rendering' => "H", 'type' => "square", 'emoji' => false],
        '🇮' => ['rendering' => "I", 'type' => "square", 'emoji' => false],
        '🇯' => ['rendering' => "J", 'type' => "square", 'emoji' => false],
        '🇰' => ['rendering' => "K", 'type' => "square", 'emoji' => false],
        '🇱' => ['rendering' => "L", 'type' => "square", 'emoji' => false],
        '🇲' => ['rendering' => "M", 'type' => "square", 'emoji' => false],
        '🇳' => ['rendering' => "N", 'type' => "square", 'emoji' => false],
        '🇴' => ['rendering' => "O", 'type' => "square", 'emoji' => false],
        '🇵' => ['rendering' => "P", 'type' => "square", 'emoji' => false],
        '🇶' => ['rendering' => "Q", 'type' => "square", 'emoji' => false],
        '🇷' => ['rendering' => "R", 'type' => "square", 'emoji' => false],
        '🇸' => ['rendering' => "S", 'type' => "square", 'emoji' => false],
        '🇹' => ['rendering' => "T", 'type' => "square", 'emoji' => false],
        '🇺' => ['rendering' => "U", 'type' => "square", 'emoji' => false],
        '🇻' => ['rendering' => "V", 'type' => "square", 'emoji' => false],
        '🇼' => ['rendering' => "W", 'type' => "square", 'emoji' => false],
        '🇽' => ['rendering' => "X", 'type' => "square", 'emoji' => false],
        '🇾' => ['rendering' => "Y", 'type' => "square", 'emoji' => false],
        '🇿' => ['rendering' => "Z", 'type' => "square", 'emoji' => false],
        '🚾' => ['rendering' => "WC", 'type' => "square", 'emoji' => true],
        '🈁' => ['rendering' => 'ココ', 'type' => "square", 'emoji' => true],
        '🈂' => ['rendering' => 'サ', 'type' => "square", 'emoji' => false],
        '🈐' => ['rendering' => '手', 'type' => "square", 'emoji' => false],
        '🈑' => ['rendering' => '字', 'type' => "square", 'emoji' => false],
        '🈒' => ['rendering' => '双', 'type' => "square", 'emoji' => false],
        '🈓' => ['rendering' => 'デ', 'type' => "square", 'emoji' => false],
        '🈔' => ['rendering' => '二', 'type' => "square", 'emoji' => false],
        '🈕' => ['rendering' => '多', 'type' => "square", 'emoji' => false],
        '🈖' => ['rendering' => '解', 'type' => "square", 'emoji' => false],
        '🈗' => ['rendering' => '天', 'type' => "square", 'emoji' => false],
        '🈘' => ['rendering' => '交', 'type' => "square", 'emoji' => false],
        '🈙' => ['rendering' => '映', 'type' => "square", 'emoji' => false],
        '🈚' => ['rendering' => '無', 'type' => "square", 'emoji' => true],
        '🈛' => ['rendering' => '料', 'type' => "square", 'emoji' => false],
        '🈜' => ['rendering' => '前', 'type' => "square", 'emoji' => false],
        '🈝' => ['rendering' => '後', 'type' => "square", 'emoji' => false],
        '🈞' => ['rendering' => '再', 'type' => "square", 'emoji' => false],
        '🈟' => ['rendering' => '新', 'type' => "square", 'emoji' => false],
        '🈠' => ['rendering' => '初', 'type' => "square", 'emoji' => false],
        '🈡' => ['rendering' => '終', 'type' => "square", 'emoji' => false],
        '🈢' => ['rendering' => '生', 'type' => "square", 'emoji' => false],
        '🈣' => ['rendering' => '販', 'type' => "square", 'emoji' => false],
        '🈤' => ['rendering' => '声', 'type' => "square", 'emoji' => false],
        '🈥' => ['rendering' => '吹', 'type' => "square", 'emoji' => false],
        '🈦' => ['rendering' => '演', 'type' => "square", 'emoji' => false],
        '🈧' => ['rendering' => '投', 'type' => "square", 'emoji' => false],
        '🈨' => ['rendering' => '捕', 'type' => "square", 'emoji' => false],
        '🈩' => ['rendering' => '一', 'type' => "square", 'emoji' => false],
        '🈪' => ['rendering' => '三', 'type' => "square", 'emoji' => false],
        '🈫' => ['rendering' => '遊', 'type' => "square", 'emoji' => false],
        '🈬' => ['rendering' => '左', 'type' => "square", 'emoji' => false],
        '🈭' => ['rendering' => '中', 'type' => "square", 'emoji' => false],
        '🈮' => ['rendering' => '右', 'type' => "square", 'emoji' => false],
        '🈯' => ['rendering' => '指', 'type' => "square", 'emoji' => true],
        '🈰' => ['rendering' => '走', 'type' => "square", 'emoji' => false],
        '🈱' => ['rendering' => '打', 'type' => "square", 'emoji' => false],
        '🈲' => ['rendering' => '禁', 'type' => "square", 'emoji' => true],
        '🈳' => ['rendering' => '空', 'type' => "square", 'emoji' => true],
        '🈴' => ['rendering' => '合', 'type' => "square", 'emoji' => true],
        '🈵' => ['rendering' => '満', 'type' => "square", 'emoji' => true],
        '🈶' => ['rendering' => '有', 'type' => "square", 'emoji' => true],
        '🈷' => ['rendering' => '月', 'type' => "square", 'emoji' => false],
        '🈸' => ['rendering' => '申', 'type' => "square", 'emoji' => true],
        '🈹' => ['rendering' => '割', 'type' => "square", 'emoji' => true],
        '🈺' => ['rendering' => '営', 'type' => "square", 'emoji' => true],
        '🈻' => ['rendering' => '配', 'type' => "square", 'emoji' => false],
        '🉐' => ['rendering' => '得', 'type' => "circle", 'emoji' => true],
        '🉑' => ['rendering' => '可', 'type' => "circle", 'emoji' => true],
    ];

    /**
     * @var array<string, string>
     */
    private array $templates;

    private bool $includeEmojis;

    /**
     * @param array{templates?:array{circle?:string,square?:string},includeEmojis?:bool} $options
     */
    public function __construct(array $options = [])
    {
        $this->templates = [
            'circle' => $options['templates']['circle'] ?? '(?)',
            'square' => $options['templates']['square'] ?? '[?]',
        ];
        $this->includeEmojis = (bool) ($options['includeEmojis'] ?? false);
    }

    /**
     * @param iterable<Char> $inputChars
     * @return iterable<Char>
     */
    public function __invoke(iterable $inputChars): iterable
    {
        $offset = 0;
        foreach ($inputChars as $char) {
            $record = self::MAPPINGS[$char->c] ?? null;
            if ($record !== null) {
                // Skip emoji characters if not included
                if ($record['emoji'] && !$this->includeEmojis) {
                    yield $char;
                    continue;
                }

                // Get template
                $template = $this->templates[$record['type']] ?? '?';
                $replacement = str_replace('?', $record['rendering'], $template);

                if ($replacement === '') {
                    yield $char;
                    continue;
                }

                // Yield each character in the replacement string
                $replacementChars = mb_str_split($replacement, 1, 'UTF-8');
                foreach ($replacementChars as $replacementChar) {
                    yield new Char($replacementChar, $offset, $char);
                    $offset += strlen($replacementChar);
                }
            } else {
                yield $char->withOffset($offset);
                $offset += strlen($char->c);
            }
        }
    }
}
